[package]
name = "quuid"
version = "0.1.0"
authors = ["tehAnswer <sergiorodriguezgijon@gmail.com>"]
license = "MIT"
description = "QUick UUID generator that digs your clipboard."

[dependencies]
uuid = { version = "0.7", features = ["v4"] }
clipboard = "0.5.0"
